name: CI

on:
  push:
    branches: [main]

jobs:
  mkdocs_build:
    name: MkDocs Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install pipenv
        run: python -m pip install pipenv

      - name: sync pipenv
        run: python -m pipenv sync --dev

      - name: build mkdocs
        run: python -m pipenv run mkdocs build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_branch: deploy
          publish_dir: ./
